import matplotlib.pyplot as plt
import networkx as nx
from meu_grafo_lista_adj import *
# Função para visualizar um grafo


def visualizar_grafo(grafo):
    G = nx.Graph()
    for v in grafo.vertices:
        G.add_node(str(v))
    for a in grafo.arestas.values():
        G.add_edge(str(a.v1.rotulo), str(a.v2.rotulo))
    nx.draw(G, with_labels=True)
    plt.show()


# Exemplo de uso ['E', 'a2', 'C', 'a7', 'M', 'a8', 'T', 'a9', 'Z']
grafo_drone = MeuGrafo()
grafo_drone.adiciona_vertice('A')
grafo_drone.adiciona_vertice('B')
grafo_drone.adiciona_vertice('C')
grafo_drone.adiciona_vertice('D')
grafo_drone.adiciona_vertice('E')
grafo_drone.adiciona_vertice('F')
grafo_drone.adiciona_vertice('G')
grafo_drone.adiciona_vertice('H')
grafo_drone.adiciona_vertice('I')
grafo_drone.adiciona_vertice('J')
grafo_drone.adiciona_vertice('K')
grafo_drone.adiciona_vertice('L')
grafo_drone.adiciona_vertice('M')
grafo_drone.adiciona_vertice('N')
grafo_drone.adiciona_vertice('O')
grafo_drone.adiciona_vertice('P')
grafo_drone.adiciona_vertice('Q')
grafo_drone.adiciona_vertice('R')
grafo_drone.adiciona_vertice('S')
grafo_drone.adiciona_vertice('T')
grafo_drone.adiciona_vertice('U')
grafo_drone.adiciona_vertice('V')
grafo_drone.adiciona_vertice('W')
grafo_drone.adiciona_vertice('X')
grafo_drone.adiciona_vertice('Y')
grafo_drone.adiciona_vertice('Z')
grafo_drone.adiciona_vertice('AA')
grafo_drone.adiciona_vertice('AB')
grafo_drone.adiciona_vertice('AC')
grafo_drone.adiciona_vertice('AD')
grafo_drone.adiciona_vertice('AE')
grafo_drone.adiciona_vertice('AF')
grafo_drone.adiciona_vertice('AG')
grafo_drone.adiciona_aresta('a1', 'A', 'B', 1)
grafo_drone.adiciona_aresta('a2', 'B', 'I', 1)
grafo_drone.adiciona_aresta('a3', 'I', 'J', 1)
grafo_drone.adiciona_aresta('a4', 'J', 'U', 1)
grafo_drone.adiciona_aresta('a5', 'U', 'V', 1)
grafo_drone.adiciona_aresta('a6', 'V', 'Y', 1)
grafo_drone.adiciona_aresta('a7', 'Y', 'X', 1)
grafo_drone.adiciona_aresta('a8', 'X', 'Z', 1)
grafo_drone.adiciona_aresta('a9', 'B', 'H', 2)
grafo_drone.adiciona_aresta('a10', 'A', 'C', 3)
grafo_drone.adiciona_aresta('a11', 'A', 'D', 2)
grafo_drone.adiciona_aresta('a12', 'D', 'E', 4)
grafo_drone.adiciona_aresta('a13', 'C', 'F', 1)
grafo_drone.adiciona_aresta('a14', 'E', 'F', 2)
grafo_drone.adiciona_aresta('a15', 'F', 'G', 3)
grafo_drone.adiciona_aresta('a16', 'H', 'G', 2)
grafo_drone.adiciona_aresta('a17', 'G', 'K', 2)
grafo_drone.adiciona_aresta('a18', 'F', 'L', 2)
grafo_drone.adiciona_aresta('a19', 'F', 'K', 3)
grafo_drone.adiciona_aresta('a20', 'E', 'M', 4)
grafo_drone.adiciona_aresta('a21', 'M', 'N', 3)
grafo_drone.adiciona_aresta('a22', 'L', 'O', 3)
grafo_drone.adiciona_aresta('a23', 'K', 'P', 2)
grafo_drone.adiciona_aresta('a24', 'K', 'I', 3)
grafo_drone.adiciona_aresta('a25', 'G', 'B', 2)
grafo_drone.adiciona_aresta('a26', 'J', 'Q', 3)
grafo_drone.adiciona_aresta('a27', 'Q', 'S', 7)
grafo_drone.adiciona_aresta('a28', 'S', 'AC', 2)
grafo_drone.adiciona_aresta('a29', 'AB', 'S', 3)
grafo_drone.adiciona_aresta('a30', 'O', 'U', 3)
grafo_drone.adiciona_aresta('a31', 'N', 'AA', 3)
grafo_drone.adiciona_aresta('a32', 'P', 'AA', 2)
grafo_drone.adiciona_aresta('a33', 'D', 'C', 2)
grafo_drone.adiciona_aresta('a34', 'R', 'Q', 3)
grafo_drone.adiciona_aresta('a35', 'P', 'R', 2)
grafo_drone.adiciona_aresta('a36', 'P', 'U', 4)
grafo_drone.adiciona_aresta('a37', 'U', 'R', 3)
grafo_drone.adiciona_aresta('a38', 'R', 'T', 2)
grafo_drone.adiciona_aresta('a39', 'T', 'W', 1)
grafo_drone.adiciona_aresta('a40', 'W', 'U', 2)
grafo_drone.adiciona_aresta('a41', 'V', 'AF', 2)
grafo_drone.adiciona_aresta('a42', 'T', 'AG', 2)
grafo_drone.adiciona_aresta('a43', 'T', 'AB', 1)
grafo_drone.adiciona_aresta('a44', 'Y', 'W', 3)
grafo_drone.adiciona_aresta('a45', 'AC', 'AD', 4)
grafo_drone.adiciona_aresta('a46', 'AD', 'X', 3)
grafo_drone.adiciona_aresta('a47', 'X', 'AE', 2)
visualizar_grafo(grafo_drone)